export const data = [
    {
        id: 1,
        name: 'The Willows',
        location: '3517 W. Gray St. Utica',
        beds: 4,
        bath: 3,
        builtArea: '330 ft2',
        area: '440/m',
        score: 4.8,
        img: require('../assets/img/imagen1.jpg'),
    },
    {
        id: 2,
        name: 'Orchard House',
        location: '2517 W. Jes St. Star',
        beds: 3,
        bath: 2,
        builtArea: '420 ft2',
        area: '550/m',
        score: 4.5,
        img: require('../assets/img/imagen2.jpg'),
    },
    {
        id: 3,
        name: 'The Hill',
        location: '5167 W. Flys St. Git',
        beds: 5,
        bath: 5,
        builtArea: '380 ft2',
        area: '640/m',
        score: 3.5,
        img: require('../assets/img/imagen3.jpg'),
    },
    {
        id: 4,
        name: 'The House',
        location: '3517 W. Gray St. Utica',
        beds: 4,
        bath: 3,
        builtArea: '380 ft2',
        area: '450/m',
        score: 3.8,
        img: require('../assets/img/imagen4.jpg'),
    },
    {
        id: 5,
        name: 'Orlan House',
        location: '2517 W. Jes St. Star',
        beds: 3,
        bath: 2,
        builtArea: '420 ft2',
        area: '550/m',
        score: 4,
        img: require('../assets/img/imagen1.jpg'),
    },
    {
        id: 6,
        name: 'The Hithon',
        location: '5167 W. Flys St. Git',
        beds: 2,
        bath: 2,
        builtArea: '320 ft2',
        area: '540/m',
        score: 3.5,
        img: require('../assets/img/imagen2.jpg'),
    }
]